// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using boutaburger.Data;

#nullable disable

namespace boutaburger.Migrations.PastOrderDb
{
    [DbContext(typeof(PastOrderDbContext))]
    partial class PastOrderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("boutaburger.Models.PastOrder", b =>
                {
                    b.Property<int>("PastOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PastOrderId"));

                    b.Property<int>("CartID")
                        .HasColumnType("int");

                    b.Property<double>("MenuPrice")
                        .HasColumnType("float");

                    b.HasKey("PastOrderId");

                    b.ToTable("PastOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
